import type { Metadata } from 'next'
import './globals.css'
import { PrismicPreview } from '@prismicio/next'
import { repositoryName } from '@/prismicio'
import { Toaster } from "@/components/ui/sonner"



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function Layout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body >
        {children} <PrismicPreview repositoryName={repositoryName} />
        {/* <div className="h-full w-full grid place-items-center"><span className="text-4xl">suspended.</span></div> */}
        <Toaster position="bottom-center" richColors closeButton />

      </body>
    </html>
  )
}
